### PR TITLE
Added strongly-typed shortcuts for all types

### PR DESCRIPTION
**Pull request by anisalibegic**
Added strongly-typed shortcuts for all types: FlashPrimary(), FlashSecondary(), FlashSuccess(), FlashDanger(), FlashWarning(), FlashInfo(), FlashLight(), FlashDark().

### CODE REVIEW

**Comment by lurumad** [comment]
Hi @grandpa-guru 

Thanks for your contibution.

I don't like too much the idea of being polute the IFlasher interface with many methods. I would prefer to create an extensions methods for different message types, so in this way our IFlasher interface is much cleaner and don't force to implement many methods.

Does make sense?

Kind regards!

**Comment by anisalibegic** [comment]
Are those extension methods going to be the part of this plugin or every user needs to create those extensions for himselft?

**Comment by lurumad** [comment]
Those extensions methods could be add to the project and every user could be reuse but we don't polute the interface.

Regards!

**Comment by anisalibegic** [comment]
I understand that you don't want to polute the interface but please make those extensions part of the plugin.

**Comment by lurumad** [comment]
Would you like to add those extensions methods and modify this PR or do you prefer I close this PR and add this change?

Regards!

**Comment by anisalibegic** [comment]
Sure, will do.

**Comment by anisalibegic** [comment]
I add those extension methods and modified my PR. I also changed the namespace of `IFlasher.cs` from `namespace Core.Flash.Abstractions` to `namespace Core.Flash` so there is no need to import `Core.Flash` and `Core.Flash.Abstractions` every time you use the Flasher, only `Core.Flash`.

**Comment by lurumad** [comment]
@grandpa-guru 

Can you change the version of Core.Flash in your PR in dependencies.props to 2.1.0?

Regards!

**Comment by anisalibegic** [comment]
Done. Updated version to 2.1.0.

**Comment by lurumad** [comment]
Thank you for your collaboration!

**Pull request merged**
